In [1]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('chained_assignment',None)

In [2]:
fpath_calendar = '../SanDiego/calendar.csv'

calendar_df = pd.read_csv(fpath_calendar)
print calendar_df.shape

(2411920, 4)

In [5]:
listingid = calendar_df.listing_id[0]

In [7]:
calendar_df[calendar_df.listing_id==listingid]

     listing_id        date available   price
0      11204286  2017-07-05         t  $49.00
1      11204286  2017-07-04         t  $49.00
2      11204286  2017-07-03         t  $49.00
3      11204286  2017-07-02         t  $49.00
4      11204286  2017-07-01         t  $49.00
5      11204286  2017-06-30         t  $49.00
6      11204286  2017-06-29         t  $49.00
7      11204286  2017-06-28         t  $49.00
8      11204286  2017-06-27         t  $49.00
9      11204286  2017-06-26         t  $49.00
10     11204286  2017-06-25         t  $49.00
11     11204286  2017-06-24         t  $49.00
12     11204286  2017-06-23         t  $49.00
13     11204286  2017-06-06         t  $49.00
14     11204286  2017-06-05         t  $49.00
15     11204286  2017-06-04         t  $49.00
16     11204286  2017-06-03         t  $49.00
17     11204286  2017-06-02         t  $49.00
18     11204286  2017-06-01         t  $49.00
19     11204286  2017-05-31         t  $49.00
20     11204286  2017-05-30         t  $49.00
21     11204286  2017-05-29         t  $49.00
22     11204286  2017-05-28         t  $49.00
23     11204286  2017-05-27         t  $49.00
24     11204286  2017-05-26         t  $49.00
25     11204286  2017-05-25         t  $49.00
26     11204286  2017-05-24         t  $49.00
27     11204286  2017-05-23         t  $49.00
28     11204286  2017-05-22         t  $49.00
29     11204286  2017-05-21         t  $49.00
..          ...         ...       ...     ...
335    11204286  2016-08-04         t  $49.00
336    11204286  2016-08-03         t  $49.00
337    11204286  2016-08-02         t  $49.00
338    11204286  2016-08-01         t  $49.00
339    11204286  2016-07-31         t  $49.00
340    11204286  2016-07-30         t  $49.00
341    11204286  2016-07-29         t  $49.00
342    11204286  2016-07-28         t  $49.00
343    11204286  2016-07-27         t  $49.00
344    11204286  2016-07-26         t  $49.00
345    11204286  2016-07-25         t  $49.00
346    11204286  2016-07-24         t  $49.00
347    11204286  2016-07-23         f     NaN
348    11204286  2016-07-22         f     NaN
349    11204286  2016-07-21         f     NaN
350    11204286  2016-07-20         t  $49.00
351    11204286  2016-07-19         t  $49.00
352    11204286  2016-07-18         t  $49.00
353    11204286  2016-07-17         t  $49.00
354    11204286  2016-07-16         t  $49.00
355    11204286  2016-07-15         t  $49.00
356    11204286  2016-07-14         t  $49.00
357    11204286  2016-07-13         t  $49.00
358    11204286  2016-07-12         t  $49.00
359    11204286  2016-07-11         t  $49.00
360    11204286  2016-07-10         t  $49.00
361    11204286  2016-07-09         f     NaN
362    11204286  2016-07-08         t  $49.00
363    11204286  2016-07-07         f     NaN
364    11204286  2016-07-06         t  $49.00

[365 rows x 4 columns]